set_property PACKAGE_PIN G16 [get_ports hdmi_out_clk]
set_property PACKAGE_PIN H22 [get_ports {hdmi_out_data[0]}]
set_property PACKAGE_PIN G22 [get_ports {hdmi_out_data[1]}]
set_property PACKAGE_PIN G17 [get_ports {hdmi_out_data[2]}]
set_property PACKAGE_PIN F17 [get_ports {hdmi_out_data[3]}]
set_property PACKAGE_PIN G15 [get_ports {hdmi_out_data[4]}]
set_property PACKAGE_PIN D15 [get_ports {hdmi_out_data[5]}]
set_property PACKAGE_PIN E15 [get_ports {hdmi_out_data[6]}]
set_property PACKAGE_PIN F18 [get_ports {hdmi_out_data[7]}]
set_property PACKAGE_PIN E18 [get_ports {hdmi_out_data[8]}]
set_property PACKAGE_PIN H17 [get_ports {hdmi_out_data[9]}]
set_property PACKAGE_PIN H18 [get_ports {hdmi_out_data[10]}]
set_property PACKAGE_PIN H19 [get_ports {hdmi_out_data[11]}]
set_property PACKAGE_PIN H20 [get_ports {hdmi_out_data[12]}]
set_property PACKAGE_PIN G19 [get_ports {hdmi_out_data[13]}]
set_property PACKAGE_PIN F19 [get_ports {hdmi_out_data[14]}]
set_property PACKAGE_PIN G20 [get_ports {hdmi_out_data[15]}]
set_property PACKAGE_PIN G21 [get_ports {hdmi_out_data[16]}]
set_property PACKAGE_PIN F21 [get_ports {hdmi_out_data[17]}]
set_property PACKAGE_PIN F22 [get_ports {hdmi_out_data[18]}]
set_property PACKAGE_PIN E21 [get_ports {hdmi_out_data[19]}]
set_property PACKAGE_PIN D21 [get_ports {hdmi_out_data[20]}]
set_property PACKAGE_PIN D22 [get_ports {hdmi_out_data[21]}]
set_property PACKAGE_PIN C22 [get_ports {hdmi_out_data[22]}]
set_property PACKAGE_PIN B21 [get_ports {hdmi_out_data[23]}]
set_property PACKAGE_PIN E20 [get_ports hdmi_out_de]
set_property PACKAGE_PIN E19 [get_ports hdmi_out_hs]
set_property PACKAGE_PIN C17 [get_ports {hdmi_rstn_tri_o[0]}]
set_property PACKAGE_PIN F16 [get_ports hdmi_out_vs]
set_property PACKAGE_PIN B22 [get_ports hdmi_i2c_scl_io]
set_property PACKAGE_PIN A22 [get_ports hdmi_i2c_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_de]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_hs]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_out_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_vs]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_rstn_tri_o[0]}]

set_property SLEW FAST [get_ports {hdmi_out_data[*]}]
set_property DRIVE 8 [get_ports {hdmi_out_data[*]}]
set_property SLEW FAST [get_ports hdmi_out_clk]
set_property SLEW FAST [get_ports hdmi_out_de]
set_property SLEW FAST [get_ports hdmi_out_hs]
set_property SLEW FAST [get_ports hdmi_out_vs]



